export enum RouteName {
  LOGIN = 'login',
  PAGE_404 = 'page-not-found',
  SHOP = 'shop',
  LIST = 'list',
  DETAILS = 'details',
  CART = 'cart',
  PAYMENT = 'payment',
  ADMIN = 'admin',
  USERS = 'users',
  ORDERS = 'orders',
  PAYMENT_PROCESS = 'payment-process',
  ADD_PRODUCT = 'add-product',
  EDIT_PRODUCT = 'edit-product',
}
